services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: streamory-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB:streamory

volumes:
  clickhouse-data:
