apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: native
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
